### ISSUE TITLE
When clicking on the buttons, nothing happens

### ISSUE THREAD

**Issue by galmoran** [ClimberAB/ClimberSelectionBar#1]
I'm on version 3.0 (Qlik **Server**)

**Comment by kfsjostrand** [comment]
Hi Galmoran,
Have you tried the latest commit that I did on the 6th of July?
What browser are you using?
Is it the field buttons or the variables radio button?
Can you provided me with an example app where you recreated the problem?
Thanks for the feedback

**Comment by kfsjostrand** [comment]
Fixed. What probably caused it was when adding a field with the expression editor. Sense added a "=" before the field name.
