### ISSUE TITLE
Date Range Picker Shows Incorrect Values

### ISSUE THREAD

**Issue by D1xieFlatline** [ClimberAB/ClimberSelectionBar#13]
The Date Range Picker is showing values for the Start and End date that are one day greater than the dates entered. 

For example, I enter a start date of 11/01/2016 and an end date of 11/30/2016:

![selection](https://cloud.githubusercontent.com/assets/26227902/23664295/333fac86-0323-11e7-9efc-34b6026daaf5.PNG)

But the date range picker shows a selected range of 11/02/2016 - 12/01/2016:
![wrong dates](https://cloud.githubusercontent.com/assets/26227902/23664296/33420daa-0323-11e7-8256-0bae536fba33.PNG)

Note that the correct range of 11/01/2016 - 11/30/2016 is being selected. 

This is happening in Firefox and Chrome.

**Comment by ClimberExtensions** [comment]
Thanks for letting us know! This should be fixed in the latest version. Please open a new issue if you still have problems.
