### ISSUE TITLE
Extension makes the application refresh the browser screen forever

### ISSUE THREAD

**Issue by jfdierckx** [ClimberAB/ClimberSelectionBar#14]
I'm experiencing issues with the Climber horizontal selection bar :

When the sheet contains a climber selection bar object, the browser screen is reloading the page forever.

I have this behaviour in Sense Desktop 3.2.1 and on a server with the sames version.

However, when trying the extension on a 3.1.1 server, it works without any problem.

Is there an incompatibility with 3.2 ?

**Comment by ClimberExtensions** [comment]
Could you try the last version? I tried to fixed the problem you are experience

**Comment by jfdierckx** [comment]
I think I'm using the last version... How can you see which version it is ?

**Comment by ClimberExtensions** [comment]
I've just uploaded a new version :). You can see the version in the about property panel or in the .qext file.

**Comment by jfdierckx** [comment]
OK, the issue has been solved with this version, thanks !

I see that the extension now mentions : "Field is a calculated dimension, initial selections not supported", so this was the reason why it was failing before ?

**Comment by jfdierckx** [comment]
I'm trying to deploy the extension on our server, but I get a failed error message. Should I remove files from the package before depoying it to a Qlik Sense server ?

**Comment by ClimberExtensions** [comment]
I've had an old workaround for a bug that reloaded the page if the selection was invalid. 
You always need to delete the extensions in QMC before you reupload a new version.
