### ISSUE TITLE
Incompatibility with Climber selection bar

### ISSUE THREAD

**Issue by paulcalvet** [ClimberAB/ClimberSelectionBar#15]
Hi,
I have two extensions in my application, cl-cards and cl-selection bar.
When I open the application, I have the message vizualisation not found on this server : cl-card
cl-selection-bar is ok.
I use Qlik Sense server v3.2.
Thanks

**Comment by ClimberExtensions** [comment]
What versions of the extensions are you using?
Be sure to download the latest from Github and install the latest version from the build folder.

**Comment by paulcalvet** [comment]
Ok sorry, it's ok with the last versions which are in the build folder.
Thanks !
