### ISSUE TITLE
Variable list type stacks options vertically, unable to place options horizontally.

### ISSUE THREAD

**Issue by kghovanlou** [ClimberAB/ClimberSelectionBar#16]
Variable list type stacks options vertically, unable to place options horizontally. Using QS 3.1 SR4.
Also when embedding in a mashup there appears to be a lot of redundant whitespace which causes scrollbars.

**Comment by ClimberExtensions** [comment]
Could you upload a screenshot? Is there any error messages in the console?

**Comment by kghovanlou** [comment]
Hi, image below. There is nothing in the console. Is there a way to make side by side? Other than that it works fine.
![capture](https://cloud.githubusercontent.com/assets/19950034/24503607/b4619d9a-154a-11e7-9d6f-d913679e79b2.JPG)

**Comment by ClimberExtensions** [comment]
It looks like an older version of the extension. Are you using the latest version of the extensions (the "Latest" folder in the build-folder of the download from GitHub)?
If so, have you tried the settings in Appearance>Appearance>Align lists? Any difference depending on which one you choose?

**Comment by kghovanlou** [comment]
That was it, I must have been using the wrong version. Thank you!!
