### ISSUE TITLE
Few lists are positioned only vertically.

### ISSUE THREAD

**Issue by mdorohin** [ClimberAB/ClimberSelectionBar#17]
Very great extention!
I can't use newest version - few lists are positioned only vertically. QS 3.2.2 SR2.
I backed to previous version.

**Comment by ClimberExtensions** [comment]
Hi, 
we have not been able to reproduce this error. Could you please provide us with some screenshots of the error and any errors in the Console (Ctrl+Shift+I in Chrome). 

Kind regards
/Michael

**Comment by mdorohin** [comment]
Hi,
I also tested new version in QS Desctop - all work good, but in QS Enterprise - screenshot:
![image](https://cloud.githubusercontent.com/assets/25058838/24854697/11be3fde-1de8-11e7-97a0-8649dbca3c85.png)
No errors in console.

**Comment by ClimberExtensions** [comment]
I've just pushed a new version to Github. Try 1.1.7. 
On Qlik Sense Server you need to delete the extension in the QMC/Extensions before you import the new version. 
If this doesn't work try to delete the visualization and recreate it.

**Comment by mdorohin** [comment]
Sorry, but I maked all your recommendation without positive result.

**Comment by ClimberExtensions** [comment]
What browser are you using?

**Comment by mdorohin** [comment]
Google Chrome 57.0.2987.133 (64-bit)

**Comment by ClimberExtensions** [comment]
Could you attach an example app with the bug? I can't recreate the bug you are experiencing.
//Karl

**Comment by mdorohin** [comment]
I installed new version (21.04.2017) and extention working good.
Thank you!
