### ISSUE TITLE
Calendar Styles not working properly

### ISSUE THREAD

**Issue by awolkovicz** [ClimberAB/ClimberSelectionBar#18]
Hi,

I installed the extension and when trying to create a Calendar, its styles seem really off and nothing like in the screenshots. Also, I don't get any error in the console neither when installing the extension or when creating an object.
![climber selection bar - calendar issue](https://cloud.githubusercontent.com/assets/14092382/24761715/99215340-1ac2-11e7-8940-7432cb0110cd.png)

**Comment by ClimberExtensions** [comment]
Hi, 
that does definitely not look right. The layout should look cleaner and the buttons should not look like something from the previous century ;-). Unfortunately we cannot reproduce your error in the current version with Qlik Sense 3.2.2. Tested with IE, Sense Desktop and Chrome browsers but maybe you are using something different? Please try removing the extension and download and install the latest version again. Make sure to only install the zip-file called "latest". Let us know how it goes!

Kind regards
/Michael

**Comment by awolkovicz** [comment]
I just included the zip that I downloaded from the Git repository, and never browsed the build folder inside.

Now it looks like a charm.

Thanks much!
