### ISSUE TITLE
Dimension values with spaces

### ISSUE THREAD

**Issue by Kielland** [ClimberAB/ClimberSelectionBar#2]
Hey

Great extension! Any hope to get a fix where dimension values will work? There was a suggestion from dwforest in branch, but I couldn't get it to work.

Thx
Tor Kielland

**Comment by kfsjostrand** [comment]
Hi Tor,
I can get it to work with dimension values that contain spaces, e.g. the "Regional Sales Mgr Name" dimension in Sales Discovery. Could you please provide an example app or a script that loads dummy data an app that recreates the problem.
Thanks for you feedback

**Comment by kfsjostrand** [comment]
Fixed. What probably caused it was when adding a field with the expression editor. Sense added a "=" before the field name.
