### ISSUE TITLE
Calculated Dimension

### ISSUE THREAD

**Issue by lincssamuel** [ClimberAB/ClimberSelectionBar#20]
Hello, 

I am trying to use conditional dimension using wildmatch(),

such as:
if(wildmatch([category], '0', [category]) to exclude certain fields. But then, the entire selection went blank. Any thought? 

Thank you!

**Comment by ClimberExtensions** [comment]
Does the calculated dimension work if you use it in a filterpane?
If it does then it would be of great help if you could attach an example app (qvf)

**Comment by lincssamuel** [comment]
@ClimberExtensions 

it works on a regular filterpane. An example here:https://drive.google.com/open?id=0B15vtwSklRWKbFZMRllaRDVDZHM (not sure how to attach)

**Comment by ClimberExtensions** [comment]
Just add an = sign in front of your expression and it should work :-)

**Comment by ClimberExtensions** [comment]
You missed the "=". Add that in front of the if statement and it will work.
