### ISSUE TITLE
DatePicker problems with some date format

### ISSUE THREAD

**Issue by jescorotero** [ClimberAB/ClimberSelectionBar#21]
We have 
SET DateFormat='DD/MM/YYYY';
then I select a Date Field with this format, and even if it works for filtering, the UI shows INVALID DATES
![image](https://cloud.githubusercontent.com/assets/1407874/25431699/f1ed2534-2a81-11e7-99b3-106e7e05eae9.png)

**Comment by mickeg** [comment]
Hi, I have tried to recreate this. Can you please attach an example app (.qvf) with this problem? 

//Mikael
