### ISSUE TITLE
Date Range Selector shows incorrect selected range

### ISSUE THREAD

**Issue by awolkovicz** [ClimberAB/ClimberSelectionBar#22]
Hi,

I applied all the suggestions mentioned in this issue: https://github.com/ClimberAB/ClimberSelectionBar/issues/19, and I'm still getting wrong dates after the selection is accepted.

I downloaded the last version:
![image](https://cloud.githubusercontent.com/assets/14092382/25441971/216030ca-2a7a-11e7-87c9-d90f83e09779.png)

I applied the changes in the default date formats:
![image](https://cloud.githubusercontent.com/assets/14092382/25441987/2b51f028-2a7a-11e7-9075-b9d4e452775d.png)

Also made sure to not to mix date formats when setting the Initial Selection and Min/Max dates:
![image](https://cloud.githubusercontent.com/assets/14092382/25441997/33c4a08e-2a7a-11e7-80fb-08ce0af0cd43.png)

Also casted the date in the load statement:
![image](https://cloud.githubusercontent.com/assets/14092382/25442016/3dd6cac0-2a7a-11e7-866d-94ff36650344.png)

And still, when making a selection like the following:
![image](https://cloud.githubusercontent.com/assets/14092382/25442030/4a6cab2e-2a7a-11e7-9601-d8f2ba0c17e9.png)

I still see wrong dates being displayed, even though the selection applied is correct:
![image](https://cloud.githubusercontent.com/assets/14092382/25442040/502a0688-2a7a-11e7-9fe3-ce25be1a593e.png)

Regards,
Agu.-

**Comment by ClimberExtensions** [comment]
I think I finally fixed this bug in version 1.1.13. If I managed to fix it, it is because the timezone of the user that causes the problem. 
Please try it and close the issue if it's this fix the problem

**Comment by awolkovicz** [comment]
Hi,

I think this is finally fixed since I tried with a few selections and the right date range is set in the calendar:
![image](https://cloud.githubusercontent.com/assets/14092382/25897150/4ac236b4-355d-11e7-8455-3a650cef75db.png)

So I'll go ahead and close the issue.

Thanks a lot!

Regards,
Agu.-
