### ISSUE TITLE
Mobile View looks not so fine

### ISSUE THREAD

**Issue by jgross31** [ClimberAB/ClimberSelectionBar#23]
Hello,

if I look your Extension on my Moble Device, it would show correct but with big white frame around the selection. It looks not so good.  Can you fix it or is it a feature ;-)

Regards
jgross

**Comment by mickeg** [comment]
Hi, jgross.

I assume you mean this issue: 
![image](https://cloud.githubusercontent.com/assets/5882196/25885874/3b8656aa-355b-11e7-835e-d660bd782cce.png) ? 

We are aware of it and it's not a feature :)

**Comment by jgross31** [comment]
Hello,
Is there something new about this topic.

greeting
Jürgen Groß

**Comment by ClimberExtensions** [comment]
Hi Jürgen,
Not at the moment. We added this to our road map, and we will be implementing this feature when it's on top of our list.
Regards
Karl

**Comment by jgross31** [comment]
Hello Karl, 
that is ok. 
Thank you and have a nice weekend
Regards
Jürgen

**Comment by richardbarakat** [comment]
Hi,

Any release date that includes this feature?

**Comment by jgross31** [comment]
Hello, Karl,
can you tell me when you're gonna fix this?
thank you 
Jürgen

**Comment by kfsjostrand** [comment]
Hello Jürgen,
This feature is added in our latest release 1.4.
Thanks for your feedback!
Karl

**Comment by jgross31** [comment]
Hello, Karl,

thank you so much. Works great. 

regards
Jürgen
