### ISSUE TITLE
Aging field not supported , as it give extra charater

### ISSUE THREAD

**Issue by paulyeo11** [ClimberAB/ClimberSelectionBar#26]
Hi Sir

I have post at QS forum :-

https://community.qlik.com/discussion/create!input.jspa?containerType=14&containerID=2156&draftID=1135466

Paul Yeo

**Comment by mickeg** [comment]
Hi, that link does not work.

Please describe your issue here instead along with your version of Sense and version of the extension.

//Mikael

**Comment by paulyeo11** [comment]
Hi Mickeg

I am using the QS ver 3.2 SR3 and the extension i download on 14 may 2017.

Box 1 the label display for
1-30 1 should be 1-30

Any way to remove the extra 1 ?

Paul Yeo



![remove 1](https://cloud.githubusercontent.com/assets/13136214/26095119/1d26c91c-3a4f-11e7-9c9e-4313d4e6eb88.png)

**Comment by kfsjostrand** [comment]
Hi Paul,
You are not using the Climber Selection bar extension, found here: http://branch.qlik.com/#!/project/5775290349fc1bfca8047ad2
It's the extension example HorizList, shipped with Qlik Sense, you are using. The numbers are the frequency count.

Regards 
Karl Fredberg Sjöstrand
