### ISSUE TITLE
Calendar Day is shifted by one

### ISSUE THREAD

**Issue by lincssamuel** [ClimberAB/ClimberSelectionBar#27]
Hello, 

I think the calendar week day is shift by one: 
![image](https://cloud.githubusercontent.com/assets/7426502/26119232/6b3999be-3a21-11e7-86d1-f65a85a99430.png)
for example, May 1 is a Monday instead of Tuesday. If the calendar starts on Sunday to Saturday, then this is fixed. 

Thank you!!
Samuel

**Comment by ClimberExtensions** [comment]
Hi Samuel, 
Thanks for your feedback. What version are you using of the Climber Selection Bar?
Could you please attach an app (.QVF) to this issue?

**Comment by lincssamuel** [comment]
Hello, 

I am not too sure which version I have, but on the date I reported this issue, I downloaded the latest version and still observe the same issue. 

Attached is the example qvf: https://drive.google.com/open?id=0B15vtwSklRWKTzdJcE94LURwMW8

Thank you so much for following up on this!
Samuel

**Comment by ClimberExtensions** [comment]
Thanks Samuel for the feedback. The bug is now fixed.
You can find the version of the extension in the property panel under About
![image](https://cloud.githubusercontent.com/assets/20192393/26714106/3dd02fae-4770-11e7-9bdd-dd8f4c480aac.png)
