### ISSUE TITLE
Initial Selection not working when extension is set to not visible

### ISSUE THREAD

**Issue by Ashima14** [ClimberAB/ClimberSelectionBar#28]
Hi, 

I was trying to implement a trigger like functionality using the extension on a server with QS version 3.0.3. The Initial Selection was working fine for all users when the extension property was set to Visible. However, when it was hidden, the initial selection defaults to the creator's at first and then clears out, immediately after full view is loaded. 

Also, to specify, the list type was Field and a single list was used.

Thanks,
Ashima

**Comment by mickeg** [comment]
Hi, we have tried to re-create this but from our end this seems to work fine. 
Can you please attach a sample qvf? And as always make sure you have the latest version of the extension.

//Mikael

**Comment by ClimberExtensions** [comment]
Closing this due to lack of feedback. If problem persists please post again.
