### ISSUE TITLE
"Variable" Function

### ISSUE THREAD

**Issue by yeulyeung** [ClimberAB/ClimberSelectionBar#29]
Hi Sir i'm a new user of Qlik. Could you mind to have a detail step about how to use "variable" Type? i have a dimension "Products" but i cannot show the value in selection bar with Type=Variable

**Comment by ClimberExtensions** [comment]
Thanks for your feedback yeulyeung!
If you are using a dimension (field) you should use the list type Field instead.
Info about fields:
http://help.qlik.com/en-US/sense/3.2/Subsystems/Hub/Content/DataSource/fields.htm
Info about variables:
http://help.qlik.com/en-US/sense/3.2/Subsystems/Hub/Content/Sheets/variables-dialog.htm
