### ISSUE TITLE
after Import on Server only the presentation tab is available.

### ISSUE THREAD

**Issue by jgross31** [ClimberAB/ClimberSelectionBar#3]
Hi,
i am new. What do i wrong.

i imported the extension on our QS server 3.0.1 and only the presentation tab is available.

On QS Desktop the tabs LIST and SELECTIONS are available. 

Thank You for some hints.

jgross31

**Comment by kfsjostrand** [comment]
I need to upgrade our test server to see if I can recreate the issue. Have you tried to delete the extension and reimport the extension?

**Comment by jgross31** [comment]
Hello,

thanks for your quick answer. Yes I delete the Extension and the I import the latest version.
Hope to hear from you,
many thanks
jgross31

**Comment by kfsjostrand** [comment]
I tested it on 3.01+Build:62.release/ms17. (Used =ProductVersion())
I now recreated the problem. IE seems to be the problem. What browser are you using?

**Comment by jgross31** [comment]
We use the IE11. thats true. 

Hope you can fix ist. This extension is really fine.

**Comment by jgross31** [comment]
Hello,

we have another problem with the QS Server 3.0.1 and the IE11. Perhaps it is the same reason. We use the BrowserControl from MS,  uses the IE11 , to embedd the Sens Apps. Now the mouse click event do not work any longer in the embedded Control.. Perhaps a hint ?
Regards
jgross31

**Comment by kfsjostrand** [comment]
This should be resolved in the latest commit. Open up a new issue if it persists.
