### ISSUE TITLE
Daterange min and max expressions off by one

### ISSUE THREAD

**Issue by awolkovicz** [ClimberAB/ClimberSelectionBar#30]
Hi,

When setting the Min and Max expressions, both are off by one (one less than they should be).

![image](https://cloud.githubusercontent.com/assets/14092382/26406728/86575e30-406f-11e7-96e2-44000f2a49ca.png)
Daterange min expression: =Date(Min({1} "Date"),'M/D/YYYY')
Daterange max expression: =Date(Max({1} "Date"),'M/D/YYYY')

I have added a "Text & image" object to check the Min and Max that were being calculated:
![image](https://cloud.githubusercontent.com/assets/14092382/26406845/e6f02e0c-406f-11e7-9dde-049f936a861d.png)

I know I can bypass this situation just by editing the the Daterange min and max expressions like as follows:
Daterange min expression: =Date(Min({1} "Date")+1,'M/D/YYYY')
Daterange max expression: =Date(Max({1} "Date")+1,'M/D/YYYY')

![image](https://cloud.githubusercontent.com/assets/14092382/26407157/b4f04486-4070-11e7-958f-c0894dfe0f1c.png)

But applying this fix is not something I feel really confident about since I'm not sure if it may happen that under some circumstance, the min and max may be off by one more than they should.

**Comment by ClimberExtensions** [comment]
Try the lastest release 1.2.0, it should fix your problem
Regards
Karl
