### ISSUE TITLE
Today expression is off by one

### ISSUE THREAD

**Issue by awolkovicz** [ClimberAB/ClimberSelectionBar#31]
Hi,

When setting the Today expression, it's off by one, because the object detects yesterday as the Today date.

![image](https://cloud.githubusercontent.com/assets/14092382/26413261/c9e3156a-4081-11e7-939f-80a085adfbb8.png)
Today expression: =Date(Today(),'M/D/YYYY')

You can check the actual date with the "Text & image" I added beneath the calendar:
![image](https://cloud.githubusercontent.com/assets/14092382/26413486/89d97562-4082-11e7-8157-2e4f57a38c18.png)

Of course, like in the other issue that I opened (https://github.com/ClimberAB/ClimberSelectionBar/issues/30), I can bypass this situation by adding one to the Today(), like as follows:
Today expression: =Date(Today()+1,'M/D/YYYY')
![image](https://cloud.githubusercontent.com/assets/14092382/26413619/e841d9b4-4082-11e7-829d-9a7b2a1f95ba.png)

So, as you can see, the Today button disappeared, since the 23rd is not Today since today is the 24th.

**Comment by ClimberExtensions** [comment]
Hi awolkovicz, what version of the extension are you using? Can you attach a QVF where the bug is recreated?

**Comment by ClimberExtensions** [comment]
Try the lastest release 1.2.0, it should fix your problem
Regards
Karl
