### ISSUE TITLE
Extension does not work in QlikSense Quick

### ISSUE THREAD

**Issue by SueB888** [ClimberAB/ClimberSelectionBar#34]
### Description

I'm using the extension in QlikSense desktop v3.2 SR3 and it works fine.  When I use it on the QlikSense Quick server, the list is blank.  No list values are displayed.  I've tried this on both Chrome and Edge browsers and the result is the same.

### Steps to Reproduce

1. Open a QlikSense Quik app
2.  Edit the sheet and drag the ClimberSelectionBar extension to the sheet
3. Select the default list type as 'Field'
4.  Select a data field

##### Expected behavior

The values in the selected data field should be displayed in list form within the extension

##### Actual behavior

The field values are not displayed in the list.  There is a blank list.
### Environment
```
[X ] Desktop
[ X] Enterprise
```
### Versions

* Browser: Microsoft Edge 38.14393.1066.0, Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
* Qlik Sense:  3.2.3
* Operating system: Windows 10 ,Windows Server 2012 R2
* [Other relevant versions]

**Comment by mickeg** [comment]
Hi! 

What version of the extension are you using? You can find that info in the About panel in the extension settings. 

Are there any error messages in the development console? (f12 in chrome) Can you provide any screenshots? Is it installed correctly on the server? 

//Mikael

**Comment by mickeg** [comment]
@SueB888 is this still a problem for you?
