### ISSUE TITLE
Filter selections not being applied

### ISSUE THREAD

**Issue by trevor-smith** [ClimberAB/ClimberSelectionBar#35]
### Description

Hello, I can't get the filters to actually apply in my sheets.  I try using any of my date fields and nothing seems to work.  I click on a custom date range or one of the pre-calcuated ones (today, last 7 days, last month, etc) and nothing happens once I do that. It just takes me right back to the sheet.  I seem to be missing the "Apply" button that's shown in your readme file. 

When I setup the filter, I just use '=CreatedDate' (one of the fields in my table).  Not sure what else I'm missing in the setup. 

Any advice is appreciated! Thanks!!

### Environment
``
QlikSense 3.2 SR4
```
### Versions

* Extension version: Downloaded today
* Browser: Chrome or Safari
* Operating system: Mac

### Screenshots
![image](https://user-images.githubusercontent.com/7464026/28142303-288b35d4-6715-11e7-98e7-fd15c3aae22a.png)

**Comment by mickeg** [comment]
Hi, yes you seem to be missing the apply button for some reason. 

Just to make sure what extension version you are using can you check the version number in the about panel of the extension? 

Do you get any error messages in the javascript console? (F12 in chrome)

/Mikael

**Comment by trevor-smith** [comment]
Hi Mikael,

Thanks for the quick response.  The version number is 1.2.1.

When I open developer tools in chrome:
![image](https://user-images.githubusercontent.com/7464026/28176091-ffef108c-67aa-11e7-9a21-0f64b0baf233.png)

**Comment by trevor-smith** [comment]
I deleted and re-added the object.  Now this is what I see. It still doesn't seem to work when I take it out of edit mode though.

![image](https://user-images.githubusercontent.com/7464026/28176209-67bf6900-67ab-11e7-81fd-53efa08139d0.png)

**Comment by mickeg** [comment]
Hi, could you send me a sample .qvf file where you have this issue? It seems like a styling error since the extension doesn't scale correctly in your screenshots.

Also you can try running the browser in incognito mode and in the developer tools console use filter setting Verbose instead of info.

mikael.gerhardsson@climber.se

//Mikael

**Comment by kbarkley** [comment]
Hello Mikael, I'm experiencing the same issue (apply button is visible but does not apply selection).  Has a resolution been found?

**Comment by mickeg** [comment]
Hi @kbarkley, that's weird. Can you send me a sample file to the email above?

**Comment by mickeg** [comment]
Hi, I have not received sample files from either of you so I am closing this issue. I can re-open it if you if you still need support.

//Mikael
