### ISSUE TITLE
Cannot import in QlikSense 3.2.4

### ISSUE THREAD

**Issue by CedricSagory** [ClimberAB/ClimberSelectionBar#36]
### Description

Impossible to import into last version 3.2.4

### Steps to Reproduce
Version 3.2.4
1. Import Zip content usind QMC/Extensions/Import

##### Actual behavior

Error Failed to Import, check log, but cannot find the log on server ???

### Environment
[ ] Enterprise

### Versions
* Browser: Chrome
* Qlik Sense: 3.2.4
* Operating system: Windows 2008 R2

### Screenshots
![failed_import_climberbar](https://user-images.githubusercontent.com/30873938/29134551-487f7458-7d37-11e7-8d23-7a49a1a9beb5.jpg)

**Comment by MGGSIDA** [comment]
Had the same problem with June Release.
My fix was to delete a previous version of the selection bar in the QMC Extensions first and then re-install. Worked well and no visualisations got lost or corrupted.
