### ISSUE TITLE
USA Flag is not coming up

### ISSUE THREAD

**Issue by SanthoshAshokkumar** [ClimberAB/ClimberSelectionBar#38]
### Description
Flag is not visible

[Description of the issue]
Tried to add Flag. I have USA & India as countries in my dataset. I tried to add it as flag from list but only India flag is coming up. But it works fine though. I am able to select & the associated fields are also working fine.
 
##### Expected behavior
USA Flag should be visible.

##### Actual behavior

USA Flag not visible (may be the image file is missing)

### Environment
```
[ ] Desktop

```
### Versions

* Extension version:
* Browser: Chrome
* Qlik Sense:  June 2017
* Operating system:   Windows 8.1
* [Other relevant versions]

### Screenshots
![image](https://user-images.githubusercontent.com/29715594/29945613-70e4d974-8e67-11e7-8132-c5ffacd0a293.png)

**Comment by mickeg** [comment]
Hi! Yes the file seems to be missing. The file name is "United-States-of-America.png", make sure you have that as well. (Even though the selection works...)

Please check the javascript console if you have any errors.
Open up sense in your web browser localhost:4848/hub and then press F12 (in chrome).

Also what version of the extension is this? Make sure you have the latest one, you can find that info in the about panel.

//Mikael

**Comment by mickeg** [comment]
Also, try finding out what image the extension is looking for by shift + ctrl + left click and chose 'Inspect' on the image. You might find some interesting info there.

//Mikael

**Comment by MichaelClimber** [comment]
No response in a long time and we can't replicate the error. Please resubmit if this is still a problem.
