### ISSUE TITLE
Define custom data ranges as a button

### ISSUE THREAD

**Issue by MGGSIDA** [ClimberAB/ClimberSelectionBar#39]
### Description

Not an issue but a question/feature request!
Is it possible to define a custom data range as a selection button? I.e. last month of current year defined by a formula or older than 90 days,...

### Steps to Reproduce

na

##### Expected behavior

Get an additional button with a customized data range or replace one or more of the existing buttons. Could be a selection additional to the existing options. So the list box for Data Range 01 would also contain 'custom' and you will receive a new box to enter the formula

##### Actual behavior

Seems to be not possible at the moment

### Environment
```

[x] Enterprise  June Release
```
### Versions

* Extension version:
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by MichaelClimber** [comment]
Hi, 
thanks for your input! It sounds like a reasonable request and we will include it in the wishlist for upcoming versions.

Kind regards

Michael
