### ISSUE TITLE
datepicker doesn't recognize my field date as valid

### ISSUE THREAD

**Issue by jescorotero** [ClimberAB/ClimberSelectionBar#4]
Hi there.  
I do love the datepicker List Type, but it doesn't work for me.   I have tried using a natural date field, a formula based field, a formatted date field but doesn't work.  What type of date field and format is this list type expecting to receive as input ?  Thks. 

I m pasting here the date and time related variables in my script:

SET TimeFormat='h:mm:ss';
SET DateFormat='DD/MM/YYYY';
SET TimestampFormat='DD/MM/YYYY h:mm:ss[.fff]';
SET FirstWeekDay=0;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='es-ES';
SET MonthNames='ene;feb;mar;abr;may;jun;jul;ago;sep;oct;nov;dic';
SET LongMonthNames='enero;febrero;marzo;abril;mayo;junio;julio;agosto;septiembre;octubre;noviembre;diciembre';
SET DayNames='lun;mar;mié;jue;vie;sáb;dom';
SET LongDayNames='lunes;martes;miércoles;jueves;viernes;sábado;domingo';

**Comment by leematthewshome** [comment]
I also love the idea of the date selector, but I cannot get it to work. Is the date required to be formatted a specific way in the data model or something? What assumptions are built into the way it applies the selections?

Whenever I hover over one of the button options it says "Invalid Date" in the from and to fields. I am in Australia and use dates in the format DD/MM/YYYY.

I did try to import the data in the specific format that your selector seems to use (ie. YYYY-MM-DD) and I even changed the app defaults to use that as a format. That seemed to make the custom range selector work, but none of the shortcut buttons work. They still show Invalid Date when you hover over them. I cannot check the javascript as it doesnt open in Notepad++ in a format that is editable.

**Comment by kfsjostrand** [comment]
Thanks for the feedback. You need to set the Today variable to a variable with a date expression, to get the buttons to work. 
To get it working you need to create a variable e.g. with definition "=MakeDate(2016,08,23)" or another date expression. Then you put the variable name in the Today variable field in the extensions property panel. Set the Field date format to DD/MM/YYYY.
I added that if the Today variable is left empty it defaults to new Date().
Hope this helps.
