### ISSUE TITLE
Can not support date format

### ISSUE THREAD

**Issue by diouck** [ClimberAB/ClimberSelectionBar#40]
### Description

Hello
I am trying to use the extension with a date format of timestemp or "2016-12-4:700:01+01"
 but it does not work. Is there a specific date format?

 
 
### Environment
```
[ ] Desktop 
### Versions

* Extension version:
* Browser: 
* Qlik Sense:  

### Screenshots

**Comment by mkmehta** [comment]
Hi,

I was able to use the extension with timestamp format. Please convert the timestamp to date first using the following expression in your Data load editor. and then use it with the reports after you load the data. This will be another column in the DLE.


DLE Code:
Date(Date#([Your Date Column], 'DD-MMM-YY hh.mm.ss.fffffffff tt'),'MM/DD/YYYY') as CD


PFA.

Thanks.



![dle_ext](https://user-images.githubusercontent.com/16457471/32018636-210d8faa-b990-11e7-81b7-2984ccb755eb.png)

**Comment by diouck** [comment]
Ok
I try this code
Date(Date#(date, 'DD-MMM-YY hh.mm.ss.fffffffff tt'),'MM/DD/YYYY') as "datemaj",

 but i have this error
Connector reply error: SQL##f - SqlState: 42883, ErrorCode: 1, ErrorMsg: ERREUR: l'opérateur n'existe pas : integer # record;
Error while executing the query

thanks

**Comment by Neil-Gabin** [comment]
Hey guys

I'm a newbie so please excuse me if I way off and this doesn't apply to your issues, but I had a similar issue and managed to get it to work.

Firstly, I tried hard coding the value for the field [Year-Month] and tried various different formats but ended up using this.
='2017-Oct'

What i found was that I had to clear the selections, save the sheet and close the sheet. Go back to the Hub and open the application a fresh and select the sheet and "hey presto" it worked.

I then change the formula to this and what do you know it worked for me

=Year(AddMonths(Now(),-1)) & '-' & Month(AddMonths(Now(),-1))

Hope this helps.

**Comment by MichaelClimber** [comment]
Solved. Closing.
