### ISSUE TITLE
Want to preselect "Year to date" as initial value but YearStart(Today()) turns 31/12/2016 as preselected value

### ISSUE THREAD

**Issue by leonbuijsman** [ClimberAB/ClimberSelectionBar#43]
### Description

Want to preselect "Year to date" as initial value but YearStart(Today()) turns 31/12/2016 as preselected value.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/33567712/32687923-3f348e86-c6c7-11e7-929e-55d5ca892de2.png)

![image](https://user-images.githubusercontent.com/33567712/32687917-2b9c564c-c6c7-11e7-9e2d-abe4a1044eaa.png)

When changing the formula to YearStart(Today())+1, it will return 2/1/2017.

##### Expected behavior

I want to preselect "Year to date"

##### Actual behavior

I get a date range which is one day before or one day after start of year.

### Environment

QlikSense September 2017 release

### Versions

* Extension version: latest
* Browser: Chrome
* Qlik Sense: September 2017 release
* Operating system: MacOS Sierra

### Screenshots

![image](https://user-images.githubusercontent.com/33567712/32687923-3f348e86-c6c7-11e7-929e-55d5ca892de2.png)

![image](https://user-images.githubusercontent.com/33567712/32687917-2b9c564c-c6c7-11e7-9e2d-abe4a1044eaa.png)

**Comment by edwardhallgren** [comment]
Hi,

This should be fixed i latest version. Please report again if it still occurs.

Br
Edward
