### ISSUE TITLE
Date Displayed as "undefined" after selection 

### ISSUE THREAD

**Issue by buscms** [ClimberAB/ClimberSelectionBar#44]
### Description

Dates selected and filters work as designed, but after applied ...range appears as undefined-undefined

### Steps to Reproduce

1. Select a date range
2. Click apply
3. ...

##### Expected behavior

Date range displayed after clicking off extension.

##### Actual behavior

Undefined-undefined shown.

### Environment
```
[ x] Desktop
[ x] Enterprise
```
### Versions

* Extension version:
* Browser: chrome
* Qlik Sense: 
* Operating system: windows 10 
![date](https://user-images.githubusercontent.com/32747808/33328659-931567be-d428-11e7-847a-cac541c9d3db.PNG)

* [Other relevant versions]

### Screenshots
![date](https://user-images.githubusercontent.com/32747808/33328738-bc056e6c-d428-11e7-8346-2f386c497792.PNG)

**Comment by edwardhallgren** [comment]
Hi,

Please try the lastest version. Reopen the issue if the problem still occurs.

Br
Edward
