### ISSUE TITLE
Date Range Picker initial selection (Variables) are not working correctly

### ISSUE THREAD

**Issue by BadihBouRjeily** [ClimberAB/ClimberSelectionBar#45]
### Date Range Picker initial selection (Variables) are not working correctly.

[Initial selection (Variables) are not showing the expected results in Date Range Picker, this was working perfectly until I installed the updated version that fixed the bug of one day difference]

### Steps to Reproduce

1. [![image](https://user-images.githubusercontent.com/34231845/33542969-d9a7a4da-d8dd-11e7-80d7-0519297e8ee8.png)
=MonthStart(AddMonths(Today()-1,-1))]
2. [![image](https://user-images.githubusercontent.com/34231845/33543012-fdc2b8b4-d8dd-11e7-8531-5e28cb3423d6.png)
=MonthEnd(AddMonths(Today()-1,-1))]

##### Expected behavior

[![image](https://user-images.githubusercontent.com/34231845/33543080-4a4cce36-d8de-11e7-8f2c-4f947c05e4e7.png)]

##### Actual behavior

[![image](https://user-images.githubusercontent.com/34231845/33543054-27f56924-d8de-11e7-91d4-56a48ead44c2.png)]

**Comment by edwardhallgren** [comment]
Hi,

Please check the latest version. This should be fixed!

Br
Edward

**Comment by BadihBouRjeily** [comment]
Thank you, yes I already did and it is working great.
