### ISSUE TITLE
Date Selections Show incorrectly

### ISSUE THREAD

**Issue by Countwise-UK** [ClimberAB/ClimberSelectionBar#49]
When selecting from ad to dates using the Date Range Picker they are displayed incorrectly

The dates shown in the Date Range Picker are always selected day + 1 day. i.e. Select Jan 1 to Jan 5 and Jan 2 to Jan 6 will be shown. The correct days are selected (Jan 1 to Jan 5) it is just the display that is wrong

### Environment
 Enterprise

### Versions
Qlik Sense 3.1 R2
QlikSenesServer 10.7.1
Qlik Sense Communication 12.2.0
Qlik Sense Common 13.1.0
.NET SDK 12.1.4
Client 3.35.5
QIX Engine 4.11.8
Service Dispatcher 12.0.6
App Migration Service 4.5.1
* Browser: Chrome
* Qlik Sense: 3.1 R2
* Operating system: Win 10
* [Other relevant versions]

**Comment by edwardhallgren** [comment]
Hi,

This should be fixed in the latest version. Please try it out.

Br
Edward
