### ISSUE TITLE
2 letter country codes not supported

### ISSUE THREAD

**Issue by mountaindude** [ClimberAB/ClimberSelectionBar#5]
Great extension!

While it of course works using country names for country selections, it is usually a good idea to use the ISO standardised country codes in the underlying data model. Some countries are spelled differently in different languages, while the ISO country codes are standardised globally.

https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

For this extension, it would therefore probably make sense to expect countries to be identified by such country codes, or even better either codes or names.

**Comment by MichaelClimber** [comment]
We have decided not to add support for this but will probably look at building a more generic solution for images instead.

Kind regards

Michael
