### ISSUE TITLE
Error symbol displayed after date range selection

### ISSUE THREAD

**Issue by kayawinfrey** [ClimberAB/ClimberSelectionBar#50]
Error symbol displayed after date range selection

![capture](https://user-images.githubusercontent.com/35847330/35453211-390e7e5c-027e-11e8-9c0b-d412fed7347e.PNG)

**Comment by edwardhallgren** [comment]
Hi,

This means that you don't have all dates between you date selection (warning because it's not a fully range). 

Br
Edward
