### ISSUE TITLE
Selections from the date range picker do not stick

### ISSUE THREAD

**Issue by rai-eml** [ClimberAB/ClimberSelectionBar#52]
### Description

Selections from the date range picker do not stick when you navigate from sheet to sheet within an app. 

##### Expected behavior

Selections should stick until they are cleared. 

##### Actual behavior

Selections are cleared after you navigate away from the sheet they were made on. This is inconsistent, sometimes one sheet later, sometimes more. 

### Environment
```
[X] Desktop
[X] Enterprise
```
### Versions

* Extension version: 1.4
* Browser: Chrome
* Qlik Sense: November (11.24.1)
* Operating system: Windows

**Comment by MichaelClimber** [comment]
This is not a behavior we have seen or been able to reproduce. Could you please check you have not set initial selections in the extension on the other sheets?

**Comment by edwardhallgren** [comment]
Reopen the issue if the problem still occurs

//Edward
