### ISSUE TITLE
mashup not working

### ISSUE THREAD

**Issue by wangxusq** [ClimberAB/ClimberSelectionBar#53]
### Description

It is OK in HUB, but show blank in the mashup

##### Expected behavior

Selections should be used in the mashup

##### Actual behavior

show blank in the mashup

### Environment
```
[ ] Desktop
[ ] Enterprise
```
### Versions

* Extension version:1.4
* Browser: Chrome
* Qlik Sense: 2018 Feb
* Operating system: windows

**Comment by edwardhallgren** [comment]
Hi, this should be fixed in version 1.4.3

Br
Edward
