### ISSUE TITLE
Year to Date

### ISSUE THREAD

**Issue by stevefewster** [ClimberAB/ClimberSelectionBar#54]
Not sure if this the right place to raise queries or not, but can I configure the default Year to Date to be offset. Ie the Companies Year to Date starts October, with the normal Qlik function I can specify the start month. 

Thanks
Steve

**Comment by MichaelClimber** [comment]
Hi Steve,
I think this is something you should solve in the actual application. Best is probably to take a look in QlikCommunity how to create good calendars in Qlik. Search for calendars and YTD and you should be able to find something. Let us know if there is anything extension specific you are curious about.

Kind regards

Michael

**Comment by lukearran** [comment]
Hello Michael,

Is it not possible to include a Year To Date off-set as a Date Range filter in the picker instead, alongside Year to date, Rolling 12 full months etc? I can easily create a calendar field with an offset, but it would be great to have a selection in the picker.

Kind Regards

Luke Arran

**Comment by MichaelClimber** [comment]
Aha, ok, then I understand your question better. We have considered the option to include custom made filters but it has not made it to the top of the list yet. Thanks for clarifying!

**Comment by lukearran** [comment]
No problem,

Thanks for your response Michael.
