### ISSUE TITLE
Automated previous selection removal

### ISSUE THREAD

**Issue by MGGSIDA** [ClimberAB/ClimberSelectionBar#55]
### Description

I have a question regarding the possibility of deleting a previous made selection.
Example:
The user selected 'year' 2018 on another dashboard. On the next dashboard I like to have 'all' 'year' selected regardless what has been selected for 'year' before. Means no filter at all.
Is this possible?

### Steps to Reproduce

1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

Selection cleared for a specific field -> 'all' should be selected, no filter

##### Actual behavior

only fixed values

### Environment
```
[ ] Desktop
[ ] Enterprise
```
### Versions

* Extension version:
* Browser: 
* Qlik Sense: 
* Operating system: 
* [Other relevant versions]

**Comment by edwardhallgren** [comment]
Hi,

What you can do is to create a new selection bar on the other sheet and set initial selection to * and initial selection mode to "on sheet".  This should clear all selections

![image](https://user-images.githubusercontent.com/27728137/37273328-b75bef5a-25d9-11e8-973c-39095cc24793.png)

![image](https://user-images.githubusercontent.com/27728137/37273337-bea13e78-25d9-11e8-9ec8-11a585f08058.png)


Br
Edward
