### ISSUE TITLE
Date Range Picker Selection Issue

### ISSUE THREAD

**Issue by CryCLL** [ClimberAB/ClimberSelectionBar#56]
There seems to be an issue with the date range picker. 

It seems you have to select one day ahead to get the entirety of today's data (or the desired end date). 

 So if I want to look at something from 3/12/2018 to 3/14/2018 I have to select 3/12/2018 to 3/15/2018. 

If the data is at the hourly level, the end date will only return for the 0th hour of the day.

**Comment by edwardhallgren** [comment]
Hi, The daterange picker only work properly with dates without timestamps. Add a field without time stamp using e.g DATE(FLOOR(MyTimestampDate)).

Br
Edward
