### ISSUE TITLE
Fonts are not properly loaded when using a mashup on an external server

### ISSUE THREAD

**Issue by MrYawe** [ClimberAB/ClimberSelectionBar#58]
### Description
The font "glyphicons-halflings-regular" is not properly loaded when using a mashup on an external server.

### Steps to Reproduce

Use the `Date range picker` component in a mashup on an external server with:
Qlik Sense Server: http://qlik-server.com
Mashup Server: http://mashup-server.com

##### Expected behavior
The font url must be:
`http://qlik-server/extensions/cl-horizontalselectionbar/lib/fonts/glyphicons-halflings-regular.woff`

##### Actual behavior

Actually the font url is:
`http://mashup-server.com/extensions/cl-horizontalselectionbar/lib/fonts/glyphicons-halflings-regular.woff`

### Environment
```
[ ] Desktop
[x] Enterprise
```
### Versions

* Extension version: 1.4.3
* Browser: Chrome 65.0.3325.181
* Qlik Sense: February 2018

**Comment by edwardhallgren** [comment]
Hi,

We will add this to our internal list of actions and inform when we have looked into this.

Br
Edward
