### ISSUE TITLE
The Extension doesn't work in Mashups

### ISSUE THREAD

**Issue by AlexanderJohr** [ClimberAB/ClimberSelectionBar#63]
### Description

The Extension doesn't work in Mashups. The Console displays this error:

```
TypeError: Cannot read property 'cell' of undefined
```

The element remains empty. The error is in this function:

```
e.getCell = function() {
                const b = a(g).parents(".qv-gridcell")[0]
                  , c = f.element(b).scope();
                return c.cell
            }
```

The function searches for a parent matching the class "qv-gridcell". But his class doesn't exist in mashups, it only exists in Qlik Sense Hub Apps.

The first element of the Qlik Sense object inside the mashup is `.qv-object-wrapper` and it also has a scope. But the `scope` does not return a `cell`. When using `.qv-object-wrapper` as the selector, the extension works at least, but it is cropped when there is to less space.

**Comment by edwardhallgren** [comment]
Hi, What version of the selection bar do you have? Br Edward

**Comment by edwardhallgren** [comment]
We have fixed this in a later version. //Edward
