### ISSUE TITLE
Not working on Qlik Sense June 2018

### ISSUE THREAD

**Issue by FaridChaud** [ClimberAB/ClimberSelectionBar#67]
It's not working on a June version of Qlik Sense.

![climberselectionbar](https://user-images.githubusercontent.com/9064926/42054995-4166b114-7aec-11e8-8a7e-b6288d93c0b0.jpg)

**Comment by supriyagangaiah** [comment]
Hi, i have upgraded Qliksense to April 2018. After adding Climber selection choosen date Range picker. 
Date picker pops up but selection is not geting applied to sheet or app.

**Comment by Lojdquist** [comment]
Hi, could you try to clear the cache and try again?

https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

**Comment by Lojdquist** [comment]
Reopen the issue if the problem remains.
