### ISSUE TITLE
Suggested Fix for Date Picker

### ISSUE THREAD

**Issue by leematthewshome** [ClimberAB/ClimberSelectionBar#7]
I have been trying to fix the problems I have had with the date range picker. Here is what I have found:

In file cl-horizontalselectionbar.js where it sets the following:
   g = b.dateToday,
This is not resulting in a valid date, so the ranges that are calculated below and associated with the shortcut selection buttons are also invalid. 

I tried setting 'g' to a valid date, but then that messed up the calendar rendering. So I created my own variable immediately below, resulting in the following:
   g = b.dateToday,
   lm = new Date().toJSON().slice(0,10),

Then, where the date ranges are set and associated with each shortcut button I substituted in this new variable as follows:
   ranges: {
         Yesterday: [k(lm).subtract(1, "days"), k(lm).subtract(1, "days")],
         "Last 7 Days": [k(lm).subtract(6, "days"), k(lm)],
         "Last 14 Days": [k(lm).subtract(13, "days"), k(lm)],
         "Last 28 Days": [k(lm).subtract(27, "days"), k(lm)],
         "Month to Date": [k(lm).startOf("month"), k(lm)],
         "Last Month": [k(lm).subtract(1, "month").startOf("month"), k(lm).subtract(1, "month").endOf("month")],
         "Year to Date": [k(lm).startOf("year"), k(lm)],
         "Rolling 12 months": i
   },
 
This seems to work, however when using the date picker in Sense to select a date range it causes the calendar to not display properly. So you need to clear the date selection before applying a new one. Once this is resolved it should be OK.

**Comment by leematthewshome** [comment]
After a lot of messing around I am almost there with working code. Attached is the file so far, with my changes flagged by //LMS in the comments. The q() function does not seem to work on my system, so I have commented out where it is called. This means once a selection is applied and I go back to select again I see the calendar for 1970. Should be able to resolve this pretty easily. But here is my progress so far. There are a few hacks in there...but its working.

[cl-horizontalselectionbar.zip](https://github.com/ClimberAB/ClimberSelectionBar/files/608058/cl-horizontalselectionbar.zip)

**Comment by kfsjostrand** [comment]
Thanks for the feedback. I added that if the Today variable is left empty it defaults to new Date().
To get it working you need to create a variable e.g. with definition "=MakeDate(2016,08,23)" or another date expression to make it work. Then you put the variable name in the Today variable field in the extensions property panel.
