### ISSUE TITLE
Not working with June 2018 release

### ISSUE THREAD

**Issue by debbpyk** [ClimberAB/ClimberSelectionBar#73]
### Description
Get invalid visualization when dragging it onto a sheet

### Steps to Reproduce
drag onto sheet

##### Expected behavior

properties to show up

##### Actual behavior

error Invalid Visualization

### Environment
```
[ ] Desktop
[ x] Enterprise
```
### Versions

* Browser: 
* Qlik Sense:  June 2018
* Operating system:  windows 
* [Other relevant versions]

### Screenshots
![image](https://user-images.githubusercontent.com/42250104/43917671-c9703d10-9bc5-11e8-933f-9b17750fa4a2.png)
![image](https://user-images.githubusercontent.com/42250104/43917683-d2cd7a80-9bc5-11e8-997c-5b01218e0914.png)

**Comment by edwardhallgren** [comment]
Hi, what version of the selection bar do you have? Br Edward

**Comment by debbpyk** [comment]
I had my client upgrade to latest extension and it worked 

On Aug 10, 2018, at 12:17 AM, Edward Hallgren <notifications@github.com> wrote:

Hi, what version of the selection bar do you have? Br Edward
