### ISSUE TITLE
Unable to Import in April 2018

### ISSUE THREAD

**Issue by aamertaimor** [ClimberAB/ClimberSelectionBar#77]
### Description
I am importing this extension in April 2018 release but i am gettting an error message that unable to import. Check Log files. I have checked the log files and there is nothing. 
Please confirm if this extension is compatible with April 2018 release
[Description of the issue]

### Steps to Reproduce
yes, by importing
1. [Step one]
2. [Step two]
3. ...

##### Expected behavior

[What you expected to happen]
should be imported
##### Actual behavior

[What actually happened]
error
### Environment
```
[ ] Desktop
[ x] Enterprise
```
### Versions

* Extension version: Don't know
* Browser: Chrome
* Qlik Sense: April 2018
* Operating system: Win
* [Other relevant versions]

**Comment by MichaelClimber** [comment]
Yes it is compatible with April 2018 release and I'm not aware of anyone else having this problem. Have you made sure your user is allowed to import extensions (i.e. it works for other extensions)? 
Use the download button in the readme section to get only the necessary files to import. 
![image](https://user-images.githubusercontent.com/31305648/44726678-8ec91200-aad8-11e8-8a01-445b3d738d8a.png)
Let us know if the problem persists.

**Comment by kfsjostrand** [comment]
Remeber to delete the previous installed version before update.
