### ISSUE TITLE
properties.js file won't pass strict mode check in IE with multiple 'defaultValue' properties appear in the same object

### ISSUE THREAD

**Issue by bohua** [ClimberAB/ClimberSelectionBar#8]
When using IE, strict mode won't show the extension at all since it violates the unique member name in object on line: 

https://github.com/ClimberAB/ClimberSelectionBar/blob/master/src/properties.js#L440
and
https://github.com/ClimberAB/ClimberSelectionBar/blob/master/src/properties.js#L448

defaultValue is given twice in the same object.

**Comment by kfsjostrand** [comment]
Thanks for the feedback! This should be resolved in the latest commit.
