### ISSUE TITLE
Selection Bar error

### ISSUE THREAD

**Issue by saiukiran** [ClimberAB/ClimberSelectionBar#80]
Climber Selection Bar extension working fine....But some time i am getting below arrow error..Can you please check.

![extension](https://user-images.githubusercontent.com/44688482/47888948-a9dc3900-de1d-11e8-954a-2dc4e7b22f5c.PNG)

**Comment by edwardhallgren** [comment]
Hi, what version of the extension do you have? What browser? Br Edward

**Comment by edwardhallgren** [comment]
Please reopen if problem still remains. Br Edward
