### ISSUE TITLE
Always One Selected value (NOV 2018) disables button

### ISSUE THREAD

**Issue by janvandersypt** [ClimberAB/ClimberSelectionBar#83]
### Description

When applying the new 'Always one Selected value' function of Nov 2018, this field can't be changed in the selection bar

### Steps to Reproduce

1. Apply the Always one Selected Value on field TESTFIELD1
2. Add TESTFIELD1 in the Selection Bar
3. Try to change the value of TESTFIELD1 in the Selection Bar

##### Expected behavior

The value should change

##### Actual behavior

THe value doesn't change

### Environment
```
[ ] Desktop
[ x] Enterprise
```
### Versions

* Extension version: 1.5.3
* Browser: Chrome
* Qlik Sense: Nov 2018 - Patch 1
* Operating system:  Windows Server 2016
* [Other relevant versions]

**Comment by kfsjostrand** [comment]
We are working on a release of the Climber Selection Bar that handles the new features introduced in Qlik Sense November 2018. This will be released most likely this week. Stay tuned

**Comment by kfsjostrand** [comment]
Fixed in v1.6.0
https://github.com/ClimberAB/ClimberSelectionBar/releases/latest
