### ISSUE TITLE
Initial Selection with comma on value

### ISSUE THREAD

**Issue by acesynolia** [ClimberAB/ClimberSelectionBar#86]
Good morning everyone,

It is more a question than an issue but I do not know where to raised it so I created a Github account to ask it here. (Sorry if I should not)

I have a field with value like:
France
Italie, Allemagne

I know that we can set 2 values on initial selection mode at put in a comma between my values.
But if one of the my value has a comma like "Italie, Allemagne", how should I managed it to make it selected on my initial selection field ?

Thank you by advance guys.

**Comment by MichaelClimber** [comment]
All support for Climber extensions are now handled by Vizlib. Please visit www.vizlib.com for more information and download of the latest versions.

That particular case you describe is most likely not handled in the extension today. It seems like something we could potentially fix for subscribing customers.
